language: cpp

os:
  - linux

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

matrix:
  include:
    - script:
      - cmake . && make -j4
      - make test
      - ./flatc
    - script: ./biicode/support/bii-travis.sh
